version: 2
jobs:
  build:
    working_directory: ~/repo/01-Authorization-RS256
    machine: true
           
    steps:
      - checkout:
         path: ~/repo

      - run: 
          name: Set .env file
          command: |
              mv .env.example .env
              sed -i "s/{DOMAIN}/$AUTH0_TEST_DOMAIN/g" .env
              sed -i "s/{AUTH0_AUDIENCE}/$AUTH0_TEST_AUDIENCE/g" .env    
              head .env
 
      - run: 
           name: background server
           command: sh exec.sh
           background: true
           
      - run:
           name: Wait until server is online
           command: |
              until $(curl --output /dev/null --silent --head --fail http://localhost:3010/api/public); do
                  sleep 5
              done
         
      - run:
          name: Clone script test
          command: git clone https://github.com/auth0-samples/api-quickstarts-tests test
          
      - run: 
          name: Prepare environment variables for test
          command: |
            cd test
            echo "AUTH0_DOMAIN=$AUTH0_TEST_DOMAIN" >> .env
            echo "API_IDENTIFIER=$AUTH0_TEST_AUDIENCE" >> .env
            echo "AUTH0_CLIENT_ID_1=$AUTH0_TEST_CLIENT_ID1" >> .env
            echo "AUTH0_CLIENT_SECRET_1=$AUTH0_TEST_CLIENT_SECRET1" >> .env
            echo "AUTH0_CLIENT_ID_2=$AUTH0_TEST_CLIENT_ID2" >> .env
            echo "AUTH0_CLIENT_SECRET_2=$AUTH0_TEST_CLIENT_SECRET2" >> .env
            echo "AUTH0_CLIENT_ID_3=$AUTH0_TEST_CLIENT_ID3" >> .env
            echo "AUTH0_CLIENT_SECRET_3=$AUTH0_TEST_CLIENT_SECRET3" >> .env
            echo "AUTH0_CLIENT_ID_4=$AUTH0_TEST_CLIENT_ID4" >> .env
            echo "AUTH0_CLIENT_SECRET_4=$AUTH0_TEST_CLIENT_SECRET4" >> .env
            echo "API_URL=http://localhost:3010" >> .env

      - run:
          name: Install test script dependency
          command: cd test && npm install 

      - run:
          name: Test
          command: cd test && npm test
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: Quickstart API Tests
