source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib' # For sinatra/json
gem 'jwt'
gem 'dotenv'
gem 'rack-cors', require: 'rack/cors'

group :test do
  gem 'minitest'
  gem 'minitest-reporters'
  gem 'rake'
  gem 'rack-test', require: 'rack/test'
end

group :development do
  gem 'guard'
  gem 'guard-minitest'
end
